"""JSON schema helpers used by the workflow."""

from typing import Any, Dict


def get_diplomatic_schema() -> Dict[str, Any]:
    """
    Get JSON schema for Step 1 diplomatic transcription output.
    Includes Regex pattern enforcement for the strict 15th-c character set.

    Returns:
        JSON schema dictionary.
    """
    # Regex Explanation:
    # ^ and $ : Start and end of string (strict match)
    # A-Za-z  : Standard Latin alphabet
    # \.,;¶·  : Allowed punctuation
    # \s      : Whitespace
    # The rest: Specific medieval Unicode glyphs and combining diacritics
    # Note: \u0305 is the combining overline ( ̅ )
    
    allowed_pattern = r"^[A-Za-z\.,;¶·⁊ſħłđꝛꝝꝫꝑꝓꝙꝰꝭıþȝ÷\u0305ͬᵃᵉⁱᵒᵘ\s]+$"

    return {
        "type": "OBJECT",
        "properties": {
            "lines": {
                "type": "ARRAY",
                "items": {
                    "type": "OBJECT",
                    "properties": {
                        "id": {
                            "type": "STRING",
                            "description": "The line ID from the input HTR (e.g., L01)."
                        },
                        "transcription": {
                            "type": "STRING",
                            "description": "Diplomatic transcription. NO 'ñ', NO hyphens, NO precomposed macrons.",
                            "pattern": allowed_pattern
                        },
                    },
                    "required": ["id", "transcription"],
                },
            }
        },
        "required": ["lines"],
    }

def get_merged_diplomatic_schema() -> Dict[str, Any]:
    """
    Get JSON schema for Step 2a merged diplomatic output.

    Defines the structure for merged text with extracted surnames
    and place names (original and anglicized forms).

    Returns:
        JSON schema dictionary for merged diplomatic format.
    """
    return {
        "type": "OBJECT",
        "properties": {
            "merged_text": {
                "type": "STRING",
                "description": "The seamless, stitched diplomatic latin text.",
            },
            "surnames": {
                "type": "ARRAY",
                "items": {"type": "STRING"},
                "description": "List of all surnames found in the text.",
            },
            "place_names": {
                "type": "ARRAY",
                "items": {
                    "type": "OBJECT",
                    "properties": {
                        "original": {"type": "STRING"},
                        "anglicized": {"type": "STRING"},
                    },
                    "required": ["original", "anglicized"],
                },
                "description": "List of place names as tuples of (original, anglicized).",
            },
            "marginal_county": {
                "type": "OBJECT",
                "properties": {
                    "original": {"type": "STRING"},
                    "anglicized": {"type": "STRING"},
                },
                "required": ["original", "anglicized"],
                "description": "The name of the county as it appears in the margin",
            },            
        },
        "required": ["merged_text", "surnames", "place_names","marginal_county"],
    }


def get_final_index_schema() -> Dict[str, Any]:
    """
    Get JSON schema for Step 4 final structured extraction output.

    Defines the comprehensive schema for structured case data including:
    - Reference information (roll, rotulus, date, term, county)
    - Cases with parties, events, locations, legal details
    - Enumerated values for counties, case types, event types, roles, etc.

    Returns:
        JSON schema dictionary for final index format.
        This is the most complex schema, defining the complete structured output.
    """
    # Original schema preserved as-is for compatibility.
    return {
        "title": "CP40 Extraction",
        "type": "object",
        "properties": {
            "TblReference": {
                "type": "object",
                "properties": {
                    "reference": {"type": "string"},
                    "dateyear": {"type": "integer"},
                    "term": {
                        "type": "string",
                        "enum": ["Michaelmas", "Hilary", "Easter", "Trinity"],
                    },
                    "County": {
                        "type": "string",
                        "enum": [
                            "Bristol",
                            "Southampton",
                            "York",
                            "Newcastle upon Tyne",
                            "Bedfordshire",
                            "Berkshire",
                            "Buckinghamshire",
                            "Cambridgeshire",
                            "Cheshire",
                            "Cornwall",
                            "Cumberland",
                            "Derbyshire",
                            "Devon",
                            "Dorset",
                            "Durham",
                            "Essex",
                            "Gloucestershire",
                            "Hampshire",
                            "Herefordshire",
                            "Hertfordshire",
                            "Huntingdonshire",
                            "Kent",
                            "Lancashire",
                            "Leicestershire",
                            "Lincolnshire",
                            "London",
                            "Middlesex",
                            "Norfolk",
                            "Northamptonshire",
                            "Northumberland",
                            "Nottinghamshire",
                            "Oxfordshire",
                            "Rutland",
                            "Shropshire",
                            "Somerset",
                            "Staffordshire",
                            "Suffolk",
                            "Surrey",
                            "Sussex",
                            "Warwickshire",
                            "Westmorland",
                            "Wiltshire",
                            "Worcestershire",
                            "Yorkshire",
                            "foreign",
                            "Wales",
                            "Kingston upon Hull",
                            "Norwich",
                            "Calais",
                            "Coventry",
                            "Lincoln",
                            "Westminster Palace",
                        ],
                    },
                },
                "required": ["reference", "dateyear", "term", "County"],
            },
            "Cases": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "TblCase": {
                            "type": "object",
                            "properties": {
                                "CaseRot": {"type": "string"},
                                "County": {
                                    "type": "string",
                                    "enum": [
                                        "Bristol",
                                        "Southampton",
                                        "York",
                                        "Newcastle upon Tyne",
                                        "Bedfordshire",
                                        "Berkshire",
                                        "Buckinghamshire",
                                        "Cambridgeshire",
                                        "Cheshire",
                                        "Cornwall",
                                        "Cumberland",
                                        "Derbyshire",
                                        "Devon",
                                        "Dorset",
                                        "Durham",
                                        "Essex",
                                        "Gloucestershire",
                                        "Hampshire",
                                        "Herefordshire",
                                        "Hertfordshire",
                                        "Huntingdonshire",
                                        "Kent",
                                        "Lancashire",
                                        "Leicestershire",
                                        "Lincolnshire",
                                        "London",
                                        "Middlesex",
                                        "Norfolk",
                                        "Northamptonshire",
                                        "Northumberland",
                                        "Nottinghamshire",
                                        "Oxfordshire",
                                        "Rutland",
                                        "Shropshire",
                                        "Somerset",
                                        "Staffordshire",
                                        "Suffolk",
                                        "Surrey",
                                        "Sussex",
                                        "Warwickshire",
                                        "Westmorland",
                                        "Wiltshire",
                                        "Worcestershire",
                                        "Yorkshire",
                                        "foreign",
                                        "Wales",
                                        "Kingston upon Hull",
                                        "Norwich",
                                        "Calais",
                                        "Coventry",
                                        "Lincoln",
                                        "Westminster Palace",
                                    ],
                                },
                                "DamClaimed": {"type": "string"},
                                "DamAwarded": {"type": "string"},
                                "WritType": {"type": "string"},
                                "CaseNotes": {"type": "string"},
                            },
                            "required": ["DamClaimed", "WritType"],
                        },
                        "TblCaseType": {
                            "type": "object",
                            "properties": {
                                "CaseType": {
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "enum": [
                                            "Abduction",
                                            "Arbitration",
                                            "Assault",
                                            "Bond",
                                            "Breach of Statute",
                                            "Contract (not service/employment, or marriage)",
                                            "Debt",
                                            "Detention of goods",
                                            "Dower",
                                            "Embracery",
                                            "Housebreaking",
                                            "Imprisonment",
                                            "Loan",
                                            "Maintenance",
                                            "Negligence",
                                            "Real action  / rents / damage to real estate",
                                            "Reckoning of Account",
                                            "Safe keeping",
                                            "Sale of goods",
                                            "Surety of peace",
                                            "Theft",
                                            "Trespass (Chattels)",
                                            "Usurpation / abuse of rights",
                                            "Namium",
                                            "Trespass (Undefined)",
                                            "Taking of goods (de bonis asportatis)",
                                            "Contract (service/apprenticeship)",
                                            "Marriage contract",
                                        ],
                                    },
                                }
                            },
                        },
                        "TblEvents": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "EventType": {
                                        "type": "string",
                                        "enum": [
                                            "abduction",
                                            "accounting",
                                            "arbitration",
                                            "arrest",
                                            "assault",
                                            "bond",
                                            "breach of statute",
                                            "payment",
                                            "breach of tenure",
                                            "charter",
                                            "contract (not service/employment)",
                                            "destruction of chattels",
                                            "negligence",
                                            "detention of goods",
                                            "disseisin",
                                            "good behaviour",
                                            "house-breaking",
                                            "imprisonment",
                                            "letters patent",
                                            "loan",
                                            "location of property",
                                            "maintenance",
                                            "marriage agreement",
                                            "property transfer",
                                            "recognizance",
                                            "release (from debt/obligation)",
                                            "rental agreement",
                                            "safe keeping",
                                            "sale of goods",
                                            "gift",
                                            "service/employment contract",
                                            "theft",
                                            "annuity",
                                            "trespass",
                                            "will",
                                            "writ",
                                            "namium",
                                            "taking of goods",
                                        ],
                                    },
                                    "EventDetails": {
                                        "type": "object",
                                        "properties": {
                                            "ValueAmount": {"type": "string"},
                                            "ValueDescription": {"type": "string"},
                                        },
                                    },
                                    "EventDate": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "Date": {"type": "string"},
                                                "DateType": {
                                                    "type": "string",
                                                    "enum": ["initial", "due", "occurred", "unknown"],
                                                },
                                            },
                                        },
                                    },
                                    "LocationDetails": {
                                        "type": "object",
                                        "properties": {
                                            "SpecificPlace": {"type": "string"},
                                            "Parish": {"type": "string"},
                                            "Ward": {
                                                "type": "string",
                                                "enum": [
                                                    "Aldersgate Ward",
                                                    "Aldgate Ward",
                                                    "Bassishaw Ward",
                                                    "Billingsgate Ward",
                                                    "Bishopsgate Ward",
                                                    "Bread Street Ward",
                                                    "Bridge Ward",
                                                    "Broad Street Ward",
                                                    "Candlewick Street Ward",
                                                    "Castle Baynard Ward",
                                                    "Cheap Ward",
                                                    "Coleman Street Ward",
                                                    "Cordwainer Street Ward",
                                                    "Cornhill Ward",
                                                    "Cripplegate Ward",
                                                    "Dowgate Ward",
                                                    "Farringdon Ward Within",
                                                    "Farringdon Ward Without",
                                                    "Langbourn Ward",
                                                    "Lime Street Ward",
                                                    "Portsoken Ward",
                                                    "Queenhithe Ward",
                                                    "Tower Ward",
                                                    "Vintry Ward",
                                                    "Walbrook Ward",
                                                ],
                                            },
                                            "County": {
                                                "type": "string",
                                                "enum": [
                                                    "Bristol",
                                                    "Southampton",
                                                    "York",
                                                    "Newcastle upon Tyne",
                                                    "Bedfordshire",
                                                    "Berkshire",
                                                    "Buckinghamshire",
                                                    "Cambridgeshire",
                                                    "Cheshire",
                                                    "Cornwall",
                                                    "Cumberland",
                                                    "Derbyshire",
                                                    "Devon",
                                                    "Dorset",
                                                    "Durham",
                                                    "Essex",
                                                    "Gloucestershire",
                                                    "Hampshire",
                                                    "Herefordshire",
                                                    "Hertfordshire",
                                                    "Huntingdonshire",
                                                    "Kent",
                                                    "Lancashire",
                                                    "Leicestershire",
                                                    "Lincolnshire",
                                                    "London",
                                                    "Middlesex",
                                                    "Norfolk",
                                                    "Northamptonshire",
                                                    "Northumberland",
                                                    "Nottinghamshire",
                                                    "Oxfordshire",
                                                    "Rutland",
                                                    "Shropshire",
                                                    "Somerset",
                                                    "Staffordshire",
                                                    "Suffolk",
                                                    "Surrey",
                                                    "Sussex",
                                                    "Warwickshire",
                                                    "Westmorland",
                                                    "Wiltshire",
                                                    "Worcestershire",
                                                    "Yorkshire",
                                                    "foreign",
                                                    "Wales",
                                                    "Kingston upon Hull",
                                                    "Norwich",
                                                    "Calais",
                                                    "Coventry",
                                                    "Lincoln",
                                                    "Westminster Palace",
                                                ],
                                            },
                                            "Country": {"type": "string"},
                                        },
                                    },
                                },
                                "required": ["EventType"],
                            },
                        },
                        "Agents": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "TblName": {
                                        "type": "object",
                                        "properties": {
                                            "Christian_name": {"type": "string"},
                                            "Surname": {"type": "string"},
                                            "Suffix": {"type": "string"},
                                        },
                                        "required": ["Surname"],
                                    },
                                    "TblAgentRole": {
                                        "type": "object",
                                        "properties": {
                                            "role": {
                                                "type": "string",
                                                "enum": [
                                                    "Accessory",
                                                    "Administrator",
                                                    "Arbitrator",
                                                    "Attorney of plaintiff",
                                                    "Attorney of defendant",
                                                    "Attorney of third party",
                                                    "Auditor",
                                                    "Chief justice",
                                                    "Clerk",
                                                    "Creditor",
                                                    "Debtor",
                                                    "Defendant",
                                                    "Essoin of defendant",
                                                    "Essoin of plaintiff",
                                                    "Executor",
                                                    "Intestator",
                                                    "Juror",
                                                    "Justice",
                                                    "Official",
                                                    "Other",
                                                    "Plaintiff",
                                                    "Surety for defendant",
                                                    "Surety of law (compurgator)",
                                                    "Surety other",
                                                    "Surety of Plaintiff",
                                                    "Testator",
                                                    "Witness",
                                                ],
                                            }
                                        },
                                    },
                                    "TblAgentStatus": {
                                        "type": "object",
                                        "required": ["AgentStatus"],
                                        "properties": {
                                            "AgentStatus": {
                                                "type": "string",
                                                "description": "Social status/Rank.",
                                                "enum": [
                                                    "burgess",
                                                    "alderman",
                                                    "exalderman",
                                                    "bailiff",
                                                    "exbailiff",
                                                    "companyofficer",
                                                    "churchwarden",
                                                    "parishclergy",
                                                    "citizen",
                                                    "companyfree",
                                                    "apprentice",
                                                    "servant",
                                                    "preacher",
                                                    "mr",
                                                    "sir",
                                                    "master",
                                                    "dr",
                                                    "parishioner",
                                                    "householder",
                                                    "gentleman",
                                                    "esquire",
                                                    "knight",
                                                    "knight bar",
                                                    "lordeccles",
                                                    "lordsec",
                                                    "bishop",
                                                    "archbishop",
                                                    "earl",
                                                    "duke",
                                                    "lady",
                                                    "dame",
                                                    "royalofficer",
                                                    "civicofficer",
                                                    "chamberlainLondon",
                                                    "mistress",
                                                    "freeco",
                                                    "father",
                                                    "sergeant",
                                                    "illegitimate",
                                                    "mother",
                                                    "clerk",
                                                    "poor",
                                                    "parishofficer",
                                                    "lodger",
                                                    "captain",
                                                    "madam",
                                                    "major",
                                                    "sister",
                                                    "gentlewoman",
                                                    "overseas",
                                                    "ltcol",
                                                    "deputy",
                                                    "constable",
                                                    "black",
                                                    "journeyman",
                                                    "inmate",
                                                    "parishchild",
                                                    "pensioner",
                                                    "drphys",
                                                    "drlaw",
                                                    "officer",
                                                    "foundling",
                                                    "papist",
                                                    "roman cathollic",
                                                    "honourable",
                                                    "beadlelist",
                                                    "RightHon",
                                                    "LordMayor",
                                                    "stranger",
                                                    "mp",
                                                    "king",
                                                    "goodwife",
                                                    "worshipful",
                                                    "baron",
                                                    "colonel",
                                                    "justice",
                                                    "yeoman",
                                                    "widow",
                                                    "wife",
                                                    "Bachelor of Law",
                                                    "canon",
                                                    "dean",
                                                    "keeper of spiritualities",
                                                    "outlaw",
                                                    "franklin",
                                                ],
                                            }
                                        },
                                    },
                                    "TblAgent": {
                                        "type": "object",
                                        "properties": {
                                            "AgentGender": {
                                                "type": "string",
                                                "enum": ["m", "f", "u", "mixed"],
                                            },
                                            "Occupation": {"type": "string"},
                                            "Relationships": {"type": "string"},
                                            "InstitutionName": {"type": "string"},
                                            "LocationDetails": {
                                                "type": "object",
                                                "properties": {
                                                    "SpecificPlace": {"type": "string"},
                                                    "Parish": {"type": "string"},
                                                    "Ward": {
                                                        "type": "string",
                                                        "enum": [
                                                            "Aldersgate Ward",
                                                            "Aldgate Ward",
                                                            "Bassishaw Ward",
                                                            "Billingsgate Ward",
                                                            "Bishopsgate Ward",
                                                            "Bread Street Ward",
                                                            "Bridge Ward",
                                                            "Broad Street Ward",
                                                            "Candlewick Street Ward",
                                                            "Castle Baynard Ward",
                                                            "Cheap Ward",
                                                            "Coleman Street Ward",
                                                            "Cordwainer Street Ward",
                                                            "Cornhill Ward",
                                                            "Cripplegate Ward",
                                                            "Dowgate Ward",
                                                            "Farringdon Ward Within",
                                                            "Farringdon Ward Without",
                                                            "Langbourn Ward",
                                                            "Lime Street Ward",
                                                            "Portsoken Ward",
                                                            "Queenhithe Ward",
                                                            "Tower Ward",
                                                            "Vintry Ward",
                                                            "Walbrook Ward",
                                                        ],
                                                    },
                                                    "County": {
                                                        "type": "string",
                                                        "enum": [
                                                            "Bristol",
                                                            "Southampton",
                                                            "York",
                                                            "Newcastle upon Tyne",
                                                            "Bedfordshire",
                                                            "Berkshire",
                                                            "Buckinghamshire",
                                                            "Cambridgeshire",
                                                            "Cheshire",
                                                            "Cornwall",
                                                            "Cumberland",
                                                            "Derbyshire",
                                                            "Devon",
                                                            "Dorset",
                                                            "Durham",
                                                            "Essex",
                                                            "Gloucestershire",
                                                            "Hampshire",
                                                            "Herefordshire",
                                                            "Hertfordshire",
                                                            "Huntingdonshire",
                                                            "Kent",
                                                            "Lancashire",
                                                            "Leicestershire",
                                                            "Lincolnshire",
                                                            "London",
                                                            "Middlesex",
                                                            "Norfolk",
                                                            "Northamptonshire",
                                                            "Northumberland",
                                                            "Nottinghamshire",
                                                            "Oxfordshire",
                                                            "Rutland",
                                                            "Shropshire",
                                                            "Somerset",
                                                            "Staffordshire",
                                                            "Suffolk",
                                                            "Surrey",
                                                            "Sussex",
                                                            "Warwickshire",
                                                            "Westmorland",
                                                            "Wiltshire",
                                                            "Worcestershire",
                                                            "Yorkshire",
                                                            "foreign",
                                                            "Wales",
                                                            "Kingston upon Hull",
                                                            "Norwich",
                                                            "Calais",
                                                            "Coventry",
                                                            "Lincoln",
                                                            "Westminster Palace",
                                                        ],
                                                    },
                                                    "Country": {"type": "string"},
                                                },
                                            },
                                        },
                                    },
                                },
                                "required": ["TblName", "TblAgentRole"],
                            },
                        },
                        "TblPleadings": {
                            "type": "array",
                            "items": {"type": "object", "properties": {"PleadingText": {"type": "string"}}},
                        },
                        "TblPostea": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "PosteaText": {"type": "string"},
                                    "Date": {"type": "string"},
                                },
                            },
                        },
                    },
                    "required": ["TblCase", "TblPleadings", "TblPostea"],
                },
            },
        },
        "required": ["Cases"],
    }

